export const phrases = {
  greeting: "Hi, {0}! 🖐😎\nMy name is DreamTrip Assistant!\nI'm gonna be your guide through the inspired world of impressions and prospects!🤩💥",
  intro: "At first i would like to ask you a few questions for get to know you better!",
  how_often_do_you_travel: "How often do you travel?",
  not_bad: "Not bad! You can more!",
  cool: "Cool! I'm sure you have a lot to tell!",
  wow: "WOW! You're the best!",
  dont_worry: "Don't worry, we're gonna improve that!",
  do_you_wanna_know_how_to_travel_more: "Do you want me to tell you about how to travel so much more ?",
  do_you_wanna_traveling_impressive: "Do you wanna travel with maximum pleasure and profit?",
  prepare_for_magic: "Great! Get ready, now i'm gonna show to you such an inspired thing...",
  opening: "*opening*",
  video: "I offer you to watch how exactly guys from our club have their's rest and try to feel it!",
  inspired_or_not: "So inspiring, doesn't it ?! You have a chance to travel the same as well!\nContinue ?",
  do_you_wanna_know_who_we_are: "You have a question for sure about who are we and what is the club we offer you, right ?",
  presentation1: "We are the biggest travel club in the world!\nAnd just a unique service you can travel chipper, better and even FOR FREE!\nWe are called DreamTrips, we have 27 worldwide travel awards as the best travel service and we are opened more then in 40 countries in a whole world!",
  presentation2: "By the way, we've become and we are still the most popular and the best travel club since 2013, in Africa, Europe, Asia and America!",
  presentation3: "И что еще круче, мы предлагаем участникам нашего клуба путешествовать и зарабатывать на этом!",
  you_know_about_us: "Отлично! Значит тебе скорее всего известно о том, что мы предлагаем участникам нашего клуба невероятные путешествия в большинство самых разнообразных мест по всему миру по самым выгодным ценам, а так же возможность путешествовать и зарабатывать на этом!",
  do_you_wanna_know_more_about_business: "Хочешь узнать больше ?",
  choose_your_best: "{0}, предлагаю тебе несколько вариантов участия в крутейшем клубе путешественников DreamTrips, из которых ты можешь выбрать наиболее интересный для себя : \n1) Путешествовать без границ, пользуясь всеми преимуществами системы\n2) Зарабатывать на путешествиях\n3) Оба варианта",
  why_did_you_discard_it: "{0}, что именно тебя смутило ?",
  only_traveling_meeting: "Супер! Хочешь узнать о всех преимуществах системы и более подробно?\nПредлагаю тебе посетить нашу онлайн встречу, где мы расскажем тебе обо всём более подробно и ответим на все интересующием тебя вопросы.",
  only_business_meeting: "Отличный выбор!\nПредлагаю тебе посетить нашу онлайн встречу, где мы расскажем тебе обо всём более подробно о том, как это работает и ответим на все интересующием тебя вопросы.",
  both_traveling_and_business_meeting: "Потрясающе! Мне нравится твой потенциал!\nПредлагаю тебе посетить нашу онлайн встречу, где мы расскажем тебе обо всём более подробно и ответим на все интересующием тебя вопросы.",
  its_not_a_big_deal: "Это не проблема!\nПредлагаю тебе посетить нашу онлайн встречу, где мы расскажем тебе обо всём более подробно и ответим на все интересующием тебя вопросы.",
  closest_meeting: "Ближайшая встреча состоится в эту субботу в 12.00 и в 20.00.\nВ какое время для тебя наиболее подходящее ?",
  see_you: "Отлично, {0}, будем рады тебя видеть {1}!  Мы напомним тебе о встрече в этом чате!\nА пока предлагаем тебе подписаться на наши страницы, для того чтобы не пропустить интересные события и новости!\nПриятно познакомиться! До скорой встречи!",
  why_you_wont_to_come: "Позволь узнать причину отсутствия...",
  we_have_meetings_every_week: "Ничего страшного, {0}! Мы проводим встречи на каждой неделе, по этому ждем тебя в слебующую субботу в то же время!",
  lets_call: "Не беда. Предлагаю тебе оставить свой email или номер телефона для того, чтобы мы связались с тобой и согласовали удобное для тебя время!",
  input_your_contact: "*введите данные ниже*",
  hope_to_see_you_next_time: "Очень жаль, надеемся тебя увидеть на следующей нашей онлайн встрече.\nА пока предлагаем тебе подписаться на наши страницы, для того чтобы не пропустить интересные события и новости!\nПриятно познакомиться!",
  we_are_gonna_contact_you: "Спасибо, {0}! Мы свяжемся с тобой в ближайшее время! =)",
  type_contact: "Напишите, пожалуйста, Ваш {0}...",
  contacts_update_success: "Спасибо {0}, мы свяжемся с тобой в ближайшее время =)\nА пока предлагаем подписаться на наши страницы в соц. сетях !",
  contacts_update_error: "Ошибка при обновлении данных. Напишите, пожалуйста на почту info@dreamtrips-team.com",
  common_reply: "Хоть я и умный Бот, но я не очень понимаю человеческий текст.\nВыбери пожалуйста вариант 😀",
  we_received_your_question: "{0}, если у Вас есть дополнительные вопросы - напишите, пожалуйста, на почту : info@dreamtrips-team.com"
};

export const buttons = {
  gogogo: `Let's go!`,
  ones_per_year: '1-2 times a year',
  three_times_per_year: '3-4 times a year',
  more_often: 'More often',
  have_never_traveling: 'Never :(',
  yes_i_want: 'Yes, i want',
  ofcourse: 'Definitely',
  sure: 'Sure',
  absolutely: 'Absolutely',
  yes_i_have_a_question: 'Yes, i have',
  no_i_know_who_you_are: 'No, i know who are you! =)',
  hundred_percent: '100%',
  im_not_sure: `I'm not sure...`,
  first_variant: 'First variant',
  second_variant: 'Second variant',
  third_variant: 'Third variant',
  too_confusing: `It's too confusing`,
  not_enough_info: 'There is to less of info',
  noon: '12.00am',
  evening: '8.00pm',
  i_wont_coming: `I won't come`,
  i_wont_be_able_at_this_day: `I won't be able on that day`,
  i_wont_be_able_at_this_time: `I won't be able on that time`,
  not_interested: `I'm not interested`,
  email: 'Email',
  phone_number: 'Phone number'
};
